name: CI/CD with Docker Deployment to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build:
        required: true
        default: "true"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set commit SHA
        id: set_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: ${{ secrets.DOCKER_REGISTRY }}

      - name: Build og-image Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ steps.set_sha.outputs.sha_short }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:buildcache
          cache-to: type=registry,mode=max,ref=${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:buildcache

      - name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_DEPLOYMENT_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
            args: "{{ EVENT_PAYLOAD.repository.full_name }} has a new built with deployment version ${{ steps.set_sha.outputs.sha_short }}."
          